spring.application.name=Application

# Banco Postgree
SPRING_DATASOURCE_URL=${DATABASE_URL}
SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Porta
server.port=${PORT:8080}
server.forward-headers-strategy=framework

# JWT
jwt.secret=${JWT_SECRET}

# Logs Security
logging.level.org.springframework.security=DEBUG