events {}

http {

    # GZIP
    gzip on;
    gzip_comp_level 6;
    gzip_min_length 1000;

    gzip_types
        application/json
        text/plain
        text/css
        application/javascript;


    # RATE LIMIT
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;


    server {

        listen 80;


        # Headers segurança

        add_header X-Frame-Options "DENY";
        add_header X-Content-Type-Options "nosniff";
        add_header X-XSS-Protection "1; mode=block";
        add_header Referrer-Policy "strict-origin-when-cross-origin";
        add_header Permissions-Policy "geolocation=(), microphone=()";

        location / {

            # Rate limit por IP

            limit_req zone=api_limit burst=20 nodelay;


            proxy_pass http://api:8080;

            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        }
    }
}