name: CI/CD

on:
  push:
    branches:
      - API

  pull_request:
    branches:
      - API

jobs:
  test:
    name: Build e Testes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Dar permissão ao Maven Wrapper
        run: chmod +x mvnw

      - name: Testes
        run: ./mvnw test

      - name: Build
        run: ./mvnw package -DskipTests
